title: Robert C Edwards
description: A trail of my trials and tribulations

url: http://robertcedwards.github.io/robertcedwards.com
baseurl: "http://robertcedwards.github.io/robertcedwards.com"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: robertcedwards
   twitter: robertcedwards
   facebook: robertcedwards
   email: robertcedwards@coactlab.com
