title: Robert C Edwards
description: A trail of my trials and tribulations

url: https://robertcedwards.com
baseurl: "https://robertcedwards.com"
paginate_path: "blog/page:num/"
permalink: blog/:title/


highlighter: rouge
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: robertcedwards
   twitter: robertcedwards
   facebook: robertcedwards
   email: robertcedwards@coactlab.com
